### ISSUE TITLE
Add format-only mode

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/crlfmt#16]
Running crlfmt with imports processing on the entire repo takes over 90 seconds; this is currently the slowest part of our lint pipeline. For comparison, running `gofmt -s` on the whole repo takes about 9 seconds. Setting `imports.Options.FormatOnly` cuts crlfmt down to 16 seconds.

We don't lose anything by setting FormatOnly when run from the linter because any missing imports would be reported instead as a failure to build. The non-formatting parts of goimports are only necessary and useful when it is being run from an editor.

**Comment by benesch** [comment]
Yeah, goimports is too slow to run in CI. There's a reason that we've historically only run gofmt in CI.
